web/RLweb/RLweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('upload_form.urls', namespace='upload_form')),
]

web/RLweb/upload_form/urls.py
from django.conf.urls import url
from upload_form import views


urlpatterns = [
        url(r'^$', views.form, name='form'),
        url(r'^complete/', views.complete, name='complete')
        ]

web/RLweb/upload_form/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from datetime import datetime


class FileNameModel(models.Model):
    file_name = models.CharField(max_length=50)
    upload_time = models.DateTimeField(default=datetime.now)

web/RLweb/upload_form/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.template.context_processors import csrf
from django.conf import settings
from upload_form.models import FileNameModel
from pyIyo.ai.rl.QAgent import QAgent
import numpy as np
import pdb
import time
import json
import sys, os


UPLOAD_DIR = os.path.dirname(os.path.abspath(__file__)) + '/static/files/'

def form(request):
    if request.method != 'POST':
        return render(request, 'upload_form/form.html')

    file = request.FILES['file']
    if not '.json' in file.name:
        return render(request, 'upload_form/error.html')

    path = os.path.join(UPLOAD_DIR, file.name)
    destination = open(path, 'wb')

    for chunk in file.chunks():
        destination.write(chunk)

    insert_data = FileNameModel(file_name = file.name)
    insert_data.save()

    return redirect('upload_form:complete')


def complete(request):
    print(request)
    dir_path = '/Users/mzntaka0/Work/9DW/IYO/reinforcement_learning/web/RLweb/upload_form/static/files/'
    result_path = '/Users/mzntaka0/Work/9DW/IYO/reinforcement_learning/web/RLweb/upload_form/static/results/'
    uploaded_file = FileNameModel.objects.latest('upload_time').file_name
    with open(dir_path+uploaded_file, 'rb') as f:
        params = json.load(f)

    q_agent = QAgent(params)
    start_time = time.time() 
    final_Q = q_agent.run()
    elapsed_time = time.time() - start_time
    final_Q['process_time'] = elapsed_time

    params['process_time'] = final_Q['process_time']
    params['output'] = final_Q['outputs']

    result_file = 'output_{}'.format(FileNameModel.objects.latest('upload_time').file_name)
    with open(result_path+result_file, 'w') as f:
        json.dump(params, f)

    return render(request, 'upload_form/complete.html', final_Q)

web/RLweb/upload_form/templates/upload_form/base.html
<!DOCTYPE html>
<html lang='ja'>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="viewport" content="content">
        <title>Q-Learning Experimenter</title>
    </head>
    <body>
        <h1><u>Q-Learning Experimenter</u></h1>

        <h2>def intro():</h2>
            <p>"""<br>
            In this page, you can experiment the Q-Learning, <br>
            using json which includes Q-Learning parameters.<br>
            """
            </p>

        <h3><font color="red">required parameters(json):</font></h3>
        <table border=1 cellpadding="2">
            <tr>
                <th>parameter</th>
                <th>description</th>
                <th>type</th>
            </tr>
            <tr>
                <td>iterations</td>
                <td>How many times<br> the agent explore the nodes<br>
                (from start to goal)</td>
                <td>[int]</td>
            </tr>
            <tr>
                <td>R</td>
                <td>Reward matrix</td>
                <td>[ndarray]</td>
            </tr>
            <tr>
                <td>goal</td>
                <td>goal node</td>
                <td>[int]</int>
            </tr>
            <tr>
                <td>alpha</td>
                <td>learning late</td>
                <td>[0.0, 1.0]</td>
            </tr>
            <tr>
                <td>gamma</td>
                <td>discount late</td>
                <td>[0.0, 1.0]</td>
            </tr>
            <tr>
                <td>tau</td>
                <td>the parameter of Boltzmann distribution</td>
                <td>[0.0, &infin;)</td>
            </tr>
            <tr>
                <td>epsilon</td>
                <td>the parameter of &epsilon;-greedy</td>
                <td>[0.0, 1.0]</td>
            </tr>
        </table>
        <br>
        <br>
        <h2>def run_QLearning():</h2>

        {% block content %}
            {{ content }}
        {% endblock %}


    </body>
</html>

web/RLweb/upload_form/templates/upload_form/complete.html
{% extends "upload_form/base.html" %}

{% block title %}upload completed{% endblock title %}
{% block content %}
    <div align="center">
        <h3 align="center">Q-Learning result</h3>
    <br>
        <table border='1'>
            <tr>
                <th>process time</th>
                <td>{{ process_time}}</td>
            </tr>
            <tr>
                <th>final Q value</th>
                <td>{{ outputs }}</td>
            </tr>
        </table>
    <br>
    <br>
        <a href="{% url 'upload_form:form' %}"><button>back</button></a>
    </div>

{% endblock content %}

web/RLweb/upload_form/templates/upload_form/error.html
{% extends "upload_form/base.html" %}

{% block title %}error page{% endblock title %}
{% block content %}
    <div align="center">
        <h2 align="center">It's not json file.
            <br>Upload json file again.</h2>
        <a href="{% url 'upload_form:form' %}"><button>back</button></a>
    </div>
{% endblock content %}

web/RLweb/upload_form/templates/upload_form/form.html
{% extends "upload_form/base.html" %}

{% block title %}uploader sample{% endblock title %}
{% block content %}
        <p>"""<br>
        Upload json file of parameter.<br>
        Then click 'run' button.<br>
        """
        </p>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="file">
        <input type="submit" value="Run">
    </form>
{% endblock content %}